/// Product importance only. Delivery is tracked independently by [AppSurface.deferred].
enum ProductPriority { a, b, c }

enum SurfaceModule {
  account,
  home,
  market,
  perp,
  chat,
  wallet,
  launchpad,
  profile,
  system,
}

enum SurfaceKind { screen, sheet, component, globalState }

final class AppSurface {
  const AppSurface({
    required this.id,
    required this.title,
    required this.path,
    required this.priority,
    required this.module,
    required this.description,
    this.kind = SurfaceKind.screen,
    this.deferred = false,
  });

  final String id;
  final String title;
  final String path;
  final ProductPriority priority;
  final SurfaceModule module;
  final String description;
  final SurfaceKind kind;
  final bool deferred;
}

abstract final class SurfaceCatalog {
  static const List<String> primaryPaths = <String>[
    '/home',
    '/market',
    '/launchpad',
    '/chat',
    '/wallet',
    '/profile',
  ];

  static const List<AppSurface> all = <AppSurface>[
    // A · Account (12)
    AppSurface(
      id: 'A1',
      title: 'Launch check',
      path: '/splash',
      priority: ProductPriority.a,
      module: SurfaceModule.account,
      description: 'Restore the session and check service availability.',
    ),
    AppSurface(
      id: 'A2',
      title: 'Onboarding',
      path: '/onboarding',
      priority: ProductPriority.b,
      module: SurfaceModule.account,
      description: 'Introduce the discover, discuss and execute loop.',
    ),
    AppSurface(
      id: 'A3',
      title: 'Sign in',
      path: '/auth',
      priority: ProductPriority.a,
      module: SurfaceModule.account,
      description: 'Choose email, social, passkey or an external wallet.',
    ),
    AppSurface(
      id: 'A4',
      title: 'Verify code',
      path: '/auth/otp',
      priority: ProductPriority.a,
      module: SurfaceModule.account,
      description: 'Enter and resend a one-time code with lockout states.',
    ),
    AppSurface(
      id: 'A5',
      title: 'Connect wallet',
      path: '/auth/wallet',
      priority: ProductPriority.a,
      module: SurfaceModule.account,
      description: 'Connect an installed wallet or scan a WalletConnect code.',
    ),
    AppSurface(
      id: 'A6',
      title: 'Create wallet',
      path: '/auth/wallet/create',
      priority: ProductPriority.a,
      module: SurfaceModule.account,
      description: 'Create an embedded wallet through the configured provider.',
    ),
    AppSurface(
      id: 'A7',
      title: 'Recovery options',
      path: '/auth/wallet/backup',
      priority: ProductPriority.b,
      module: SurfaceModule.account,
      description: 'Show only recovery methods supported by the active wallet.',
    ),
    AppSurface(
      id: 'A8',
      title: 'Recovery phrase',
      path: '/auth/wallet/seed',
      priority: ProductPriority.a,
      module: SurfaceModule.account,
      description: 'Sensitive phrase reveal with explicit capability checks.',
    ),
    AppSurface(
      id: 'A9',
      title: 'Verify recovery',
      path: '/auth/wallet/seed/verify',
      priority: ProductPriority.a,
      module: SurfaceModule.account,
      description: 'Verify selected recovery words before completion.',
    ),
    AppSurface(
      id: 'A10',
      title: 'Import wallet',
      path: '/auth/wallet/import',
      priority: ProductPriority.a,
      module: SurfaceModule.account,
      description: 'Import or watch an existing address when supported.',
    ),
    AppSurface(
      id: 'A11',
      title: 'Protect your account',
      path: '/auth/security',
      priority: ProductPriority.b,
      module: SurfaceModule.account,
      description: 'Configure MFA, passkey and device lock.',
    ),
    AppSurface(
      id: 'A12',
      title: 'Set your identity',
      path: '/auth/profile',
      priority: ProductPriority.b,
      module: SurfaceModule.account,
      description: 'Choose a private alias, interests and notifications.',
    ),

    // B · Home (9)
    AppSurface(
      id: 'B1',
      title: 'Home',
      path: '/home',
      priority: ProductPriority.a,
      module: SurfaceModule.home,
      description: 'Portfolio context and the cross-product activity feed.',
    ),
    AppSurface(
      id: 'B2',
      title: 'Net worth',
      path: '/home/net-worth',
      priority: ProductPriority.b,
      module: SurfaceModule.home,
      description: 'Asset history split across chains and trading accounts.',
    ),
    AppSurface(
      id: 'B3',
      title: 'Notifications',
      path: '/notifications',
      priority: ProductPriority.a,
      module: SurfaceModule.home,
      description: 'Trading, community, security and system updates.',
    ),
    AppSurface(
      id: 'B4',
      title: 'Search',
      path: '/search',
      priority: ProductPriority.a,
      module: SurfaceModule.home,
      description: 'Search assets, Core perp markets, groups and people.',
    ),
    AppSurface(
      id: 'B5',
      title: 'Scan to pay',
      path: '/pay',
      priority: ProductPriority.a,
      module: SurfaceModule.home,
      description: 'A product priority, deferred from the current release.',
      deferred: true,
    ),
    AppSurface(
      id: 'B6',
      title: 'Receive payment',
      path: '/pay/receive',
      priority: ProductPriority.b,
      module: SurfaceModule.home,
      description: 'B product priority, deferred from this release.',
      deferred: true,
    ),
    AppSurface(
      id: 'B7',
      title: 'Confirm payment',
      path: '/pay/confirm',
      priority: ProductPriority.b,
      module: SurfaceModule.home,
      description: 'B product priority, deferred from this release.',
      deferred: true,
    ),
    AppSurface(
      id: 'B8',
      title: 'Add cash',
      path: '/onramp',
      priority: ProductPriority.c,
      module: SurfaceModule.home,
      description: 'C product priority, deferred from the current release.',
      deferred: true,
    ),
    AppSurface(
      id: 'B9',
      title: 'Security activity',
      path: '/home/security',
      priority: ProductPriority.b,
      module: SurfaceModule.home,
      description: 'Concrete wallet and account events without a risk score.',
    ),

    // C · Spot market (9)
    AppSurface(
      id: 'C1',
      title: 'Market',
      path: '/market',
      priority: ProductPriority.a,
      module: SurfaceModule.market,
      description: 'Spot discovery with a separate Core perp mode.',
    ),
    AppSurface(
      id: 'C2',
      title: 'Token details',
      path: '/market/token',
      priority: ProductPriority.a,
      module: SurfaceModule.market,
      description: 'Price, chart, contract facts and community context.',
    ),
    AppSurface(
      id: 'C3',
      title: 'Full chart',
      path: '/market/chart',
      priority: ProductPriority.a,
      module: SurfaceModule.market,
      description: 'Landscape-ready chart with periods and indicators.',
    ),
    AppSurface(
      id: 'C5',
      title: 'Holder distribution',
      path: '/market/holders',
      priority: ProductPriority.b,
      module: SurfaceModule.market,
      description: 'Concentration and holder clusters with source time.',
    ),
    AppSurface(
      id: 'C6',
      title: 'Trading activity',
      path: '/market/trades',
      priority: ProductPriority.b,
      module: SurfaceModule.market,
      description: 'Recent trades and large transaction facts.',
    ),
    AppSurface(
      id: 'C7',
      title: 'Edit watchlist',
      path: '/market/watchlist',
      priority: ProductPriority.b,
      module: SurfaceModule.market,
      description: 'Order, group and remove watched assets.',
    ),
    AppSurface(
      id: 'C9',
      title: 'Price alerts',
      path: '/market/alerts',
      priority: ProductPriority.b,
      module: SurfaceModule.market,
      description: 'Create and review price alerts.',
    ),
    AppSurface(
      id: 'C10',
      title: 'New pairs',
      path: '/market/new',
      priority: ProductPriority.a,
      module: SurfaceModule.market,
      description: 'Fresh pools with concrete contract facts.',
    ),
    AppSurface(
      id: 'C11',
      title: 'Smart money',
      path: '/market/smart-money',
      priority: ProductPriority.b,
      module: SurfaceModule.market,
      description: 'Activity from addresses the user follows.',
    ),

    // D · Hyperliquid Core perp (12)
    AppSurface(
      id: 'D1',
      title: 'Perpetuals',
      path: '/perp',
      priority: ProductPriority.a,
      module: SurfaceModule.perp,
      description: 'BTC, ETH and SOL Core markets.',
    ),
    AppSurface(
      id: 'D2',
      title: 'Trade perpetual',
      path: '/perp/trade',
      priority: ProductPriority.a,
      module: SurfaceModule.perp,
      description: 'Chart, order book and order ticket.',
    ),
    AppSurface(
      id: 'D3',
      title: 'Review order',
      path: '/perp/confirm',
      priority: ProductPriority.a,
      module: SurfaceModule.perp,
      description: 'Exact order, margin and liquidation context.',
    ),
    AppSurface(
      id: 'D4',
      title: 'Positions',
      path: '/perp/positions',
      priority: ProductPriority.a,
      module: SurfaceModule.perp,
      description: 'Current positions, PnL, leverage and liquidation price.',
    ),
    AppSurface(
      id: 'D5',
      title: 'Manage position',
      path: '/perp/position',
      priority: ProductPriority.a,
      module: SurfaceModule.perp,
      description: 'Margin, leverage and reduce-only position actions.',
    ),
    AppSurface(
      id: 'D6',
      title: 'Open orders',
      path: '/perp/orders',
      priority: ProductPriority.a,
      module: SurfaceModule.perp,
      description: 'Current orders with amend and cancel states.',
    ),
    AppSurface(
      id: 'D7',
      title: 'Trade history',
      path: '/perp/history',
      priority: ProductPriority.b,
      module: SurfaceModule.perp,
      description: 'Fills, realized PnL and funding history.',
    ),
    AppSurface(
      id: 'D8',
      title: 'Margin account',
      path: '/perp/account',
      priority: ProductPriority.a,
      module: SurfaceModule.perp,
      description: 'Equity, available margin and liquidation risk.',
    ),
    AppSurface(
      id: 'D9',
      title: 'Transfer balance',
      path: '/perp/transfer',
      priority: ProductPriority.b,
      module: SurfaceModule.perp,
      description: 'Move value between spot and perp accounts.',
    ),
    AppSurface(
      id: 'D10',
      title: 'Deposit & withdraw',
      path: '/perp/deposit',
      priority: ProductPriority.b,
      module: SurfaceModule.perp,
      description: 'Official Hyperliquid bridge context only.',
    ),
    AppSurface(
      id: 'D11',
      title: 'Funding rates',
      path: '/perp/funding',
      priority: ProductPriority.b,
      module: SurfaceModule.perp,
      description: 'Funding history and next settlement.',
    ),
    AppSurface(
      id: 'D12',
      title: 'Perpetual risk',
      path: '/perp/risk',
      priority: ProductPriority.b,
      module: SurfaceModule.perp,
      description: 'First-use leverage and liquidation acknowledgement.',
    ),

    // E · Chat and voice (13)
    AppSurface(
      id: 'E1',
      title: 'Chats',
      path: '/chat',
      priority: ProductPriority.a,
      module: SurfaceModule.chat,
      description: 'Group, direct and voice conversations.',
    ),
    AppSurface(
      id: 'E2',
      title: 'Group conversation',
      path: '/chat/group',
      priority: ProductPriority.a,
      module: SurfaceModule.chat,
      description: 'Replies, reactions, mentions and pinned context.',
    ),
    AppSurface(
      id: 'E3',
      title: 'Voice room',
      path: '/chat/voice',
      priority: ProductPriority.a,
      module: SurfaceModule.chat,
      description: 'Embedded room with clear microphone state.',
    ),
    AppSurface(
      id: 'E4',
      title: 'Direct message',
      path: '/chat/dm',
      priority: ProductPriority.a,
      module: SurfaceModule.chat,
      description: 'Private conversation without an E2EE claim.',
    ),
    AppSurface(
      id: 'E5',
      title: 'Token message card',
      path: '/preview/token-card',
      priority: ProductPriority.a,
      module: SurfaceModule.chat,
      description: 'Source-timestamped asset context inside a conversation.',
      kind: SurfaceKind.component,
    ),
    AppSurface(
      id: 'E7',
      title: 'Contract facts',
      path: '/preview/contract-facts',
      priority: ProductPriority.a,
      module: SurfaceModule.chat,
      description: 'Verifiable contract facts and source time.',
      kind: SurfaceKind.sheet,
    ),
    AppSurface(
      id: 'E8',
      title: 'Group details',
      path: '/chat/group-info',
      priority: ProductPriority.b,
      module: SurfaceModule.chat,
      description: 'Group summary, announcement and members.',
    ),
    AppSurface(
      id: 'E9',
      title: 'Asset snapshot card',
      path: '/preview/asset-message',
      priority: ProductPriority.b,
      module: SurfaceModule.chat,
      description: 'A shared trade snapshot without live-price persistence.',
      kind: SurfaceKind.component,
    ),
    AppSurface(
      id: 'E10',
      title: 'Voice room expanded',
      path: '/chat/voice/full',
      priority: ProductPriority.b,
      module: SurfaceModule.chat,
      description: 'Speakers, listeners and host controls.',
    ),
    AppSurface(
      id: 'E11',
      title: 'Message requests',
      path: '/chat/requests',
      priority: ProductPriority.b,
      module: SurfaceModule.chat,
      description: 'Accept, ignore or report new direct messages.',
    ),
    AppSurface(
      id: 'E12',
      title: 'Search messages',
      path: '/chat/search',
      priority: ProductPriority.b,
      module: SurfaceModule.chat,
      description: 'Search by person, group and date.',
    ),
    AppSurface(
      id: 'E13',
      title: 'Meetings',
      path: '/chat/meeting',
      priority: ProductPriority.c,
      module: SurfaceModule.chat,
      description: 'Video and meeting capability is planned later.',
      deferred: true,
    ),
    AppSurface(
      id: 'E14',
      title: 'Assistant',
      path: '/preview/assistant',
      priority: ProductPriority.c,
      module: SurfaceModule.chat,
      description: 'Community assistant is planned later.',
      kind: SurfaceKind.component,
      deferred: true,
    ),

    // F · Wallet (20)
    AppSurface(
      id: 'F1',
      title: 'Wallet',
      path: '/wallet',
      priority: ProductPriority.a,
      module: SurfaceModule.wallet,
      description: 'Portfolio and wallet actions across supported accounts.',
    ),
    AppSurface(
      id: 'F2',
      title: 'Asset details',
      path: '/wallet/asset',
      priority: ProductPriority.a,
      module: SurfaceModule.wallet,
      description: 'Holdings, cost basis and activity by chain.',
    ),
    AppSurface(
      id: 'F3',
      title: 'Choose asset',
      path: '/wallet/send',
      priority: ProductPriority.a,
      module: SurfaceModule.wallet,
      description: 'Select an available asset to send.',
    ),
    AppSurface(
      id: 'F4',
      title: 'Choose recipient',
      path: '/wallet/send/to',
      priority: ProductPriority.a,
      module: SurfaceModule.wallet,
      description: 'Address, name, scan and recipient facts.',
    ),
    AppSurface(
      id: 'F5',
      title: 'Confirm transfer',
      path: '/wallet/send/confirm',
      priority: ProductPriority.a,
      module: SurfaceModule.wallet,
      description: 'Amount, fee and simulated asset changes.',
    ),
    AppSurface(
      id: 'F6',
      title: 'Receive',
      path: '/wallet/receive',
      priority: ProductPriority.a,
      module: SurfaceModule.wallet,
      description: 'Address, QR and network warning.',
    ),
    AppSurface(
      id: 'F7',
      title: 'Swap',
      path: '/wallet/swap',
      priority: ProductPriority.a,
      module: SurfaceModule.wallet,
      description: 'Provider quote, slippage and simulation.',
    ),
    AppSurface(
      id: 'F8',
      title: 'Swap quote details',
      path: '/wallet/swap/route',
      priority: ProductPriority.b,
      module: SurfaceModule.wallet,
      description: 'Final quote and fee composition when available.',
    ),
    AppSurface(
      id: 'F9',
      title: 'Bridge',
      path: '/wallet/bridge',
      priority: ProductPriority.b,
      module: SurfaceModule.wallet,
      description: 'Provider-selected cross-chain route.',
    ),
    AppSurface(
      id: 'F10',
      title: 'Bridge progress',
      path: '/wallet/bridge/status',
      priority: ProductPriority.b,
      module: SurfaceModule.wallet,
      description: 'Source confirmation, relay and destination progress.',
    ),
    AppSurface(
      id: 'F11',
      title: 'Signing review',
      path: '/preview/signing-review',
      priority: ProductPriority.a,
      module: SurfaceModule.wallet,
      description: 'The single app-owned intent review surface.',
      kind: SurfaceKind.sheet,
    ),
    AppSurface(
      id: 'F12',
      title: 'Transaction result',
      path: '/wallet/transaction',
      priority: ProductPriority.b,
      module: SurfaceModule.wallet,
      description: 'Pending, successful, failed and unknown submission states.',
    ),
    AppSurface(
      id: 'F13',
      title: 'Transaction history',
      path: '/wallet/history',
      priority: ProductPriority.b,
      module: SurfaceModule.wallet,
      description: 'Filter and inspect wallet activity.',
    ),
    AppSurface(
      id: 'F14',
      title: 'Manage wallets',
      path: '/wallet/manage',
      priority: ProductPriority.b,
      module: SurfaceModule.wallet,
      description: 'Switch, rename and manage wallet capabilities.',
    ),
    AppSurface(
      id: 'F15',
      title: 'DApp browser',
      path: '/wallet/dapp',
      priority: ProductPriority.b,
      module: SurfaceModule.wallet,
      description: 'Wallet-aware browser with domain context.',
    ),
    AppSurface(
      id: 'F16',
      title: 'Approval request',
      path: '/preview/approval',
      priority: ProductPriority.a,
      module: SurfaceModule.wallet,
      description: 'Unlimited approval warning with a limited option.',
      kind: SurfaceKind.sheet,
    ),
    AppSurface(
      id: 'F17',
      title: 'App permissions',
      path: '/wallet/approvals',
      priority: ProductPriority.b,
      module: SurfaceModule.wallet,
      description: 'Review and revoke token permissions.',
    ),
    AppSurface(
      id: 'F18',
      title: 'DApps',
      path: '/wallet/dapps',
      priority: ProductPriority.c,
      module: SurfaceModule.wallet,
      description: 'Bookmarks and recent apps.',
      deferred: true,
    ),
    AppSurface(
      id: 'F19',
      title: 'Networks',
      path: '/wallet/networks',
      priority: ProductPriority.b,
      module: SurfaceModule.wallet,
      description: 'Enabled chains, testnets and RPC health.',
    ),
    AppSurface(
      id: 'F20',
      title: 'Transaction protection',
      path: '/wallet/protection',
      priority: ProductPriority.c,
      module: SurfaceModule.wallet,
      description: 'Plain-language wallet protection controls.',
      deferred: true,
    ),

    // G · Launchpad (4)
    AppSurface(
      id: 'G1',
      title: 'Launchpad',
      path: '/launchpad',
      priority: ProductPriority.a,
      module: SurfaceModule.launchpad,
      description: 'A clear future-phase placeholder.',
    ),
    AppSurface(
      id: 'G2',
      title: 'Launches',
      path: '/launchpad/list',
      priority: ProductPriority.c,
      module: SurfaceModule.launchpad,
      description: 'Project discovery is planned later.',
      deferred: true,
    ),
    AppSurface(
      id: 'G3',
      title: 'Launch details',
      path: '/launchpad/detail',
      priority: ProductPriority.c,
      module: SurfaceModule.launchpad,
      description: 'Participation is planned later.',
      deferred: true,
    ),
    AppSurface(
      id: 'G4',
      title: 'Apply to launch',
      path: '/launchpad/apply',
      priority: ProductPriority.c,
      module: SurfaceModule.launchpad,
      description: 'Project applications are planned later.',
      deferred: true,
    ),

    // H · Profile and settings (16)
    AppSurface(
      id: 'H1',
      title: 'Profile',
      path: '/profile',
      priority: ProductPriority.a,
      module: SurfaceModule.profile,
      description: 'Alias, privacy posture and account summary.',
    ),
    AppSurface(
      id: 'H2',
      title: 'Edit profile',
      path: '/profile/edit',
      priority: ProductPriority.b,
      module: SurfaceModule.profile,
      description: 'Alias, image, bio and visibility.',
    ),
    AppSurface(
      id: 'H3',
      title: 'Privacy',
      path: '/profile/privacy',
      priority: ProductPriority.a,
      module: SurfaceModule.profile,
      description: 'Anonymous mode and portfolio sharing controls.',
    ),
    AppSurface(
      id: 'H4',
      title: 'Copy permissions',
      path: '/profile/copy',
      priority: ProductPriority.b,
      module: SurfaceModule.profile,
      description: 'Who may copy and within what limit.',
    ),
    AppSurface(
      id: 'H5',
      title: 'Security',
      path: '/profile/security',
      priority: ProductPriority.a,
      module: SurfaceModule.profile,
      description: 'MFA, lock, recovery and login activity.',
    ),
    AppSurface(
      id: 'H6',
      title: 'Devices & sessions',
      path: '/profile/devices',
      priority: ProductPriority.b,
      module: SurfaceModule.profile,
      description: 'Review and sign out active devices.',
    ),
    AppSurface(
      id: 'H7',
      title: 'Recovery backup',
      path: '/profile/recovery',
      priority: ProductPriority.a,
      module: SurfaceModule.profile,
      description: 'Capability-gated sensitive recovery access.',
    ),
    AppSurface(
      id: 'H8',
      title: 'Social recovery',
      path: '/profile/social-recovery',
      priority: ProductPriority.b,
      module: SurfaceModule.profile,
      description: 'Guardian configuration when supported.',
    ),
    AppSurface(
      id: 'H9',
      title: 'Notification settings',
      path: '/profile/notifications',
      priority: ProductPriority.b,
      module: SurfaceModule.profile,
      description: 'Trading, community and account alerts.',
    ),
    AppSurface(
      id: 'H10',
      title: 'Connections',
      path: '/profile/connections',
      priority: ProductPriority.b,
      module: SurfaceModule.profile,
      description: 'Followed people and followers.',
    ),
    AppSurface(
      id: 'H11',
      title: 'Blocked',
      path: '/profile/blocked',
      priority: ProductPriority.b,
      module: SurfaceModule.profile,
      description: 'Blocked people, contracts and domains.',
    ),
    AppSurface(
      id: 'H12',
      title: 'Settings',
      path: '/profile/settings',
      priority: ProductPriority.b,
      module: SurfaceModule.profile,
      description: 'Language, currency, theme and data.',
    ),
    AppSurface(
      id: 'H13',
      title: 'About & legal',
      path: '/profile/about',
      priority: ProductPriority.b,
      module: SurfaceModule.profile,
      description: 'Version, agreements, disclosures and licenses.',
    ),
    AppSurface(
      id: 'H14',
      title: 'Help',
      path: '/profile/help',
      priority: ProductPriority.b,
      module: SurfaceModule.profile,
      description: 'Guides, support and service status.',
    ),
    AppSurface(
      id: 'H15',
      title: 'Rewards',
      path: '/profile/rewards',
      priority: ProductPriority.c,
      module: SurfaceModule.profile,
      description: 'Rewards are planned later.',
      deferred: true,
    ),
    AppSurface(
      id: 'H16',
      title: 'Invite friends',
      path: '/profile/referral',
      priority: ProductPriority.c,
      module: SurfaceModule.profile,
      description: 'Invites are planned later.',
      deferred: true,
    ),

    // I · System surfaces (8)
    AppSurface(
      id: 'I1',
      title: 'You’re offline',
      path: '/system/offline',
      priority: ProductPriority.a,
      module: SurfaceModule.system,
      description: 'Differentiate full network loss from provider failure.',
      kind: SurfaceKind.globalState,
    ),
    AppSurface(
      id: 'I2',
      title: 'Service unavailable',
      path: '/system/error',
      priority: ProductPriority.a,
      module: SurfaceModule.system,
      description: 'A recoverable server error state.',
      kind: SurfaceKind.globalState,
    ),
    AppSurface(
      id: 'I3',
      title: 'Update required',
      path: '/system/update',
      priority: ProductPriority.a,
      module: SurfaceModule.system,
      description: 'A blocking minimum-version update.',
      kind: SurfaceKind.sheet,
    ),
    AppSurface(
      id: 'I4',
      title: 'Maintenance',
      path: '/system/maintenance',
      priority: ProductPriority.b,
      module: SurfaceModule.system,
      description: 'Planned maintenance and service timing.',
      kind: SurfaceKind.globalState,
    ),
    AppSurface(
      id: 'I5',
      title: 'Feature unavailable here',
      path: '/system/region',
      priority: ProductPriority.a,
      module: SurfaceModule.system,
      description: 'Region restrictions without blocking eligible surfaces.',
      kind: SurfaceKind.globalState,
    ),
    AppSurface(
      id: 'I6',
      title: 'Permission needed',
      path: '/system/permission',
      priority: ProductPriority.b,
      module: SurfaceModule.system,
      description:
          'Explain camera, notifications or microphone before requesting.',
      kind: SurfaceKind.sheet,
    ),
    AppSurface(
      id: 'I7',
      title: 'Global feedback',
      path: '/preview/toast',
      priority: ProductPriority.b,
      module: SurfaceModule.system,
      description: 'Success, warning and error feedback.',
      kind: SurfaceKind.component,
    ),
    AppSurface(
      id: 'I8',
      title: 'Loading states',
      path: '/preview/loading',
      priority: ProductPriority.b,
      module: SurfaceModule.system,
      description: 'List, detail and chart skeletons.',
      kind: SurfaceKind.component,
    ),
  ];

  static AppSurface byId(String id) =>
      all.firstWhere((surface) => surface.id == id);

  static AppSurface byPath(String path) =>
      all.firstWhere((surface) => surface.path == path);

  static List<AppSurface> forModule(SurfaceModule module) =>
      all.where((surface) => surface.module == module).toList(growable: false);
}
